In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import sklearn
import os

import itertools

In [23]:
df_CIBIL = pd.read_csv("E:/Anirban_Ghosh/INPUT/sal_semp_TRAIN1dnd11.CSV",encoding='latin1')

In [24]:
df_CIBIL.shape

(303851, 122)

In [6]:
df_CIBIL.head()

,true_prospect_id__c,EMAIL_AVAILABLE_FLAG,PROSPECT_EMAIL_DOMAIN_COMPANY_FL,ENRICHED_GENDER,ENRICHED_AGE,PROSPECT_SOURCE_NAME,ENRICHED_SPECIALIZATION,ENRICHED_DEGREE,ENRICHED_QUALIFICATION,ENRICHED_CURRENT_INDUSTRY,...,dpd_90_flag,dpd_15_flag,dpd_30_flag,cibil_score1,CIBIL_EMAIL_DOMAIN_COMPANY_FLAG1,ADDRESS_WITH_COMPANY_FLAG1,HIGHEST_EDUCATION_INSTI,WORK_EXPERIENE_BAND,ANNUAL_SALARY_BAND,TIER_FINAL
0,PM_BIU00000848004966,1,1,MISSING,35,INTERNAL_SME,N,N,N,N,...,1,0,1,720,N,N,N,INFO_MISSING,INFO_MISSING,TIER1
1,PM_BIU00000651901434,1,0,MISSING,37,MBK_WALLET_PROSPECT,N,N,N,N,...,0,0,0,793,INFO_MISSING,INFO_MISSING,N,INFO_MISSING,INFO_MISSING,TIER1
2,PM_BIU90000171492755,1,0,MALE,42,PAN_INCREMENTAL,N,N,N,N,...,0,0,0,779,INFO_MISSING,INFO_MISSING,N,INFO_MISSING,INFO_MISSING,TIER4
3,PM_BIU90000106873081,0,0,MALE,42,PAN_INCREMENTAL,N,N,N,N,...,0,0,0,776,N,N,N,INFO_MISSING,INFO_MISSING,TIER1
4,PM_BIU00000901000874,1,0,MALE,31,CONTACT_DATA,N,N,N,N,...,0,0,0,750,INFO_MISSING,INFO_MISSING,N,INFO_MISSING,INFO_MISSING,TIER4

In [7]:
pd.set_option('display.max_columns',10000)
pd.set_option('display.max_rows',10000)
df_CIBIL.head()

,true_prospect_id__c,EMAIL_AVAILABLE_FLAG,PROSPECT_EMAIL_DOMAIN_COMPANY_FL,ENRICHED_GENDER,ENRICHED_AGE,PROSPECT_SOURCE_NAME,ENRICHED_SPECIALIZATION,ENRICHED_DEGREE,ENRICHED_QUALIFICATION,ENRICHED_CURRENT_INDUSTRY,ENRICHED_CURRENT_COMPANY,ENRICHED_DESIGNATION,PROSPECT_SAL_FLAG,PROSPECT_TRAV_FLAG,PROSPECT_ECOM_FLAG,PROSPECT_AMO_FLAG,PROSPECT_INV_FLAG,PROSPECT_POSTPAID_FLAG,PROSPECT_PREPAID_FLAG,PROSPECT_INSURANCE_FLAG,PROSPECT_MBK_FLAG,PROSPECT_OTH_FLAG,PROSPECT_DTH_FLAG,TOTAL_PROSPECT_SOURCES,TOTAL_PROSPECT_AND_RA_SOURCES,PPL_OFFER_FLAG,CIBIL_BUREAU_HIT_FLAG,BUREAU_CIBIL_SALARIED_FLAG,CIBIL_SCORE,TOTAL_NO_OF_LOANS_CIBIL,TOTAL_NO_OF_LIVE_LOANS_CIBIL,TOTAL_NO_OF_CLOSED_LOANS_CIBIL,TOTAL_SANCTIONED_AMOUNT_CIBIL,TOTAL_POS_CIBIL,CD_TOTAL_LOANS_CIBIL,CD_LIVE_LOANS_CIBIL,CD_CLOSED_LOANS_CIBIL,CD_POS_CIBIL,PL_TOTAL_LOANS_CIBIL,PL_LIVE_LOANS_CIBIL,PL_CLOSED_LOANS_CIBIL,PL_POS_CIBIL,CC_TOTAL_LOANS_CIBIL,CC_LIVE_LOANS_CIBIL,CC_CLOSED_LOANS_CIBIL,CC_POS_CIBIL,HL_TOTAL_LOANS_CIBIL,HL_LIVE_LOANS_CIBIL,HL_CLOSED_LOANS_CIBIL,HL_POS_CIBIL,LAP_TOTAL_LOANS_CIBIL,LAP_LIVE_LOANS_CIBIL,LAP_CLOSED_LOANS_CIBIL,LAP_POS_CIBIL,BL_TOTAL_LOANS_CIBIL,BL_LIVE_LOANS_CIBIL,BL_CLOSED_LOANS_CIBIL,BL_POS_CIBIL,GL_TOTAL_LOANS_CIBIL,GL_LIVE_LOANS_CIBIL,GL_CLOSED_LOANS_CIBIL,GL_POS_CIBIL,OTH_LIVE_LOANS_CIBIL,OTH_CLOSED_LOANS_CIBIL,OTH_POS_CIBIL,ECOM_CREDIT_CARD_FLAG,ECOM_CREDIT_CARD_PREMIUM_FLAG,ECOM_DEBIT_CARD_FLAG,ECOM_DEBIT_CARD_PREMIUM_FLAG,ECOM_NB_FLAG,ECOM_NB_PREMIUM_FLAG,ECOM_CREDIT_CARD_HDFC_FLAG,ECOM_CREDIT_CARD_ICICI_FLAG,ECOM_CREDIT_CARD_CITI_FLAG,ECOM_CREDIT_CARD_SBI_FLAG,ECOM_CREDIT_CARD_AMEX_FLAG,ECOM_CREDIT_CARD_AXIS_FLAG,ECOM_CREDIT_CARD_HSBC_FLAG,ECOM_DEBIT_CARD_HDFC_FLAG,ECOM_DEBIT_CARD_ICICI_FLAG,ECOM_DEBIT_CARD_CITI_FLAG,ECOM_DEBIT_CARD_SBI_FLAG,ECOM_DEBIT_CARD_AMEX_FLAG,ECOM_DEBIT_CARD_AXIS_FLAG,ECOM_DEBIT_CARD_HSBC_FLAG,ECOM_NB_HDFC_FLAG,ECOM_NB_ICICI_FLAG,ECOM_NB_CITI_FLAG,ECOM_NB_SBI_FLAG,ECOM_NB_AMEX_FLAG,ECOM_NB_AXIS_FLAG,ECOM_NB_HSBC_FLAG,PAYU_FLAG,PAYU_CREDIT_CARD_USER,PAYU_DEBIT_CARD_USER,PAYU_NET_BANKING_USER,BUREAU_RECENCY,TOT_SACAMT,num_live_PL,live_HL_flag,num_live_CC,TOT_UNSEC_live_nbr,TOT_live_OSBAL,TOT_live_SACAMT,TOT_SEC_live_nbr,TOT_live_nbr,cibil_score_bureau,live_CC_Bal,live_CC_Sacamt,RT_LIVE_OSBAL_2_SACAMT,live_CC_utilization,RT_live_2_TOT_SACAMT,dpd_90_flag,dpd_15_flag,dpd_30_flag,cibil_score1,CIBIL_EMAIL_DOMAIN_COMPANY_FLAG1,ADDRESS_WITH_COMPANY_FLAG1,HIGHEST_EDUCATION_INSTI,WORK_EXPERIENE_BAND,ANNUAL_SALARY_BAND,TIER_FINAL
0,PM_BIU00000848004966,1,1,MISSING,35,INTERNAL_SME,N,N,N,N,N,N,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,23,10,13,3359468,1070704,0,0,0,0,1,0,1,0,6,4,2,450119,0,0,0,0,0,0,0,0,2,2,0,330016,9,0,9,0,4,1,290569,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,N,N,2,3419468,0,0,2,2,1070802,1637728,0,11,0,180022,644728,0.65,27.9221,0.47,1,0,1,720,N,N,N,INFO_MISSING,INFO_MISSING,TIER1
1,PM_BIU00000651901434,1,0,MISSING,37,MBK_WALLET_PROSPECT,N,N,N,N,N,N,0,0,0,0,0,0,0,0,1,0,0,1,1,0,1,0,793,5,3,2,2028818,1012397,2,1,1,34664,2,1,1,993153,1,1,0,-15420,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,N,N,12,2028818,1,0,1,2,1012397,1404828,0,3,793,-15420,252828,0.72,-6.0990,0.69,0,0,0,793,INFO_MISSING,INFO_MISSING,N,INFO_MISSING,INFO_MISSING,TIER1
2,PM_BIU90000171492755,1,0,MALE,42,PAN_INCREMENTAL,N,N,N,N,N,N,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,0,779,4,1,3,278223,23788,1,0,1,0,0,0,0,0,2,1,1,23788,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,N,N,14,278223,0,0,1,0,23788,29807,0,1,779,23788,29807,0.79,79.8067,0.10,0,0,0,779,INFO_MISSING,INFO_MISSING,N,INFO_MISSING,INFO_MISSING,TIER4
3,PM_BIU90000106873081,0,0,MALE,42,PAN_INCREMENTAL,N,N,N,N,N,N,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,0,0,2,2,0,702950,608324,0,0,0,0,0,0,0,0,1,1,0,-2500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,N,N,4,702950,0,0,1,1,608324,702950,0,2,0,-2500,2950,0.86,-84.7457,1.00,0,0,0,776,N,N,N,INFO_MISSING,INFO_MISSING,TIER1
4,PM_BIU00000901000874,1,0,MALE,31,CONTACT_DATA,N,N,N,N,N,N,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,0,0,8,3,5,1135193,627938,0,0,0,0,2,1,1,31108,6,2,4,596830,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,N,N,4,1135193,1,0,2,1,627938,938045,0,3,0,596830,738045,0.66,80.8663,0.82,0,0,0,750,INFO_MISSING,INFO_MISSING,N,INFO_MISSING,INFO_MISSING,TIER4

In [8]:
df_CIBIL['TIER_FINAL'].unique()

array(['TIER1', 'TIER4', 'TIER2', 'TIER3'], dtype=object)

In [9]:
sd=['true_prospect_id__c','PROSPECT_SOURCE_NAME']

In [26]:
df_CIBIL2_2=df_CIBIL.drop(sd,axis=1)

In [27]:
df_CIBIL2_2.head()

,EMAIL_AVAILABLE_FLAG,PROSPECT_EMAIL_DOMAIN_COMPANY_FL,ENRICHED_GENDER,ENRICHED_AGE,ENRICHED_SPECIALIZATION,ENRICHED_DEGREE,ENRICHED_QUALIFICATION,ENRICHED_CURRENT_INDUSTRY,ENRICHED_CURRENT_COMPANY,ENRICHED_DESIGNATION,PROSPECT_SAL_FLAG,PROSPECT_TRAV_FLAG,PROSPECT_ECOM_FLAG,PROSPECT_AMO_FLAG,PROSPECT_INV_FLAG,PROSPECT_POSTPAID_FLAG,PROSPECT_PREPAID_FLAG,PROSPECT_INSURANCE_FLAG,PROSPECT_MBK_FLAG,PROSPECT_OTH_FLAG,PROSPECT_DTH_FLAG,TOTAL_PROSPECT_SOURCES,TOTAL_PROSPECT_AND_RA_SOURCES,PPL_OFFER_FLAG,CIBIL_BUREAU_HIT_FLAG,BUREAU_CIBIL_SALARIED_FLAG,CIBIL_SCORE,TOTAL_NO_OF_LOANS_CIBIL,TOTAL_NO_OF_LIVE_LOANS_CIBIL,TOTAL_NO_OF_CLOSED_LOANS_CIBIL,TOTAL_SANCTIONED_AMOUNT_CIBIL,TOTAL_POS_CIBIL,CD_TOTAL_LOANS_CIBIL,CD_LIVE_LOANS_CIBIL,CD_CLOSED_LOANS_CIBIL,CD_POS_CIBIL,PL_TOTAL_LOANS_CIBIL,PL_LIVE_LOANS_CIBIL,PL_CLOSED_LOANS_CIBIL,PL_POS_CIBIL,CC_TOTAL_LOANS_CIBIL,CC_LIVE_LOANS_CIBIL,CC_CLOSED_LOANS_CIBIL,CC_POS_CIBIL,HL_TOTAL_LOANS_CIBIL,HL_LIVE_LOANS_CIBIL,HL_CLOSED_LOANS_CIBIL,HL_POS_CIBIL,LAP_TOTAL_LOANS_CIBIL,LAP_LIVE_LOANS_CIBIL,LAP_CLOSED_LOANS_CIBIL,LAP_POS_CIBIL,BL_TOTAL_LOANS_CIBIL,BL_LIVE_LOANS_CIBIL,BL_CLOSED_LOANS_CIBIL,BL_POS_CIBIL,GL_TOTAL_LOANS_CIBIL,GL_LIVE_LOANS_CIBIL,GL_CLOSED_LOANS_CIBIL,GL_POS_CIBIL,OTH_LIVE_LOANS_CIBIL,OTH_CLOSED_LOANS_CIBIL,OTH_POS_CIBIL,ECOM_CREDIT_CARD_FLAG,ECOM_CREDIT_CARD_PREMIUM_FLAG,ECOM_DEBIT_CARD_FLAG,ECOM_DEBIT_CARD_PREMIUM_FLAG,ECOM_NB_FLAG,ECOM_NB_PREMIUM_FLAG,ECOM_CREDIT_CARD_HDFC_FLAG,ECOM_CREDIT_CARD_ICICI_FLAG,ECOM_CREDIT_CARD_CITI_FLAG,ECOM_CREDIT_CARD_SBI_FLAG,ECOM_CREDIT_CARD_AMEX_FLAG,ECOM_CREDIT_CARD_AXIS_FLAG,ECOM_CREDIT_CARD_HSBC_FLAG,ECOM_DEBIT_CARD_HDFC_FLAG,ECOM_DEBIT_CARD_ICICI_FLAG,ECOM_DEBIT_CARD_CITI_FLAG,ECOM_DEBIT_CARD_SBI_FLAG,ECOM_DEBIT_CARD_AMEX_FLAG,ECOM_DEBIT_CARD_AXIS_FLAG,ECOM_DEBIT_CARD_HSBC_FLAG,ECOM_NB_HDFC_FLAG,ECOM_NB_ICICI_FLAG,ECOM_NB_CITI_FLAG,ECOM_NB_SBI_FLAG,ECOM_NB_AMEX_FLAG,ECOM_NB_AXIS_FLAG,ECOM_NB_HSBC_FLAG,PAYU_FLAG,PAYU_CREDIT_CARD_USER,PAYU_DEBIT_CARD_USER,PAYU_NET_BANKING_USER,BUREAU_RECENCY,TOT_SACAMT,num_live_PL,live_HL_flag,num_live_CC,TOT_UNSEC_live_nbr,TOT_live_OSBAL,TOT_live_SACAMT,TOT_SEC_live_nbr,TOT_live_nbr,cibil_score_bureau,live_CC_Bal,live_CC_Sacamt,RT_LIVE_OSBAL_2_SACAMT,live_CC_utilization,RT_live_2_TOT_SACAMT,dpd_90_flag,dpd_15_flag,dpd_30_flag,cibil_score1,CIBIL_EMAIL_DOMAIN_COMPANY_FLAG1,ADDRESS_WITH_COMPANY_FLAG1,HIGHEST_EDUCATION_INSTI,WORK_EXPERIENE_BAND,ANNUAL_SALARY_BAND,TIER_FINAL
0,1,1,MISSING,35,N,N,N,N,N,N,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,23,10,13,3359468,1070704,0,0,0,0,1,0,1,0,6,4,2,450119,0,0,0,0,0,0,0,0,2,2,0,330016,9,0,9,0,4,1,290569,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,N,N,2,3419468,0,0,2,2,1070802,1637728,0,11,0,180022,644728,0.65,27.9221,0.47,1,0,1,720,N,N,N,INFO_MISSING,INFO_MISSING,TIER1
1,1,0,MISSING,37,N,N,N,N,N,N,0,0,0,0,0,0,0,0,1,0,0,1,1,0,1,0,793,5,3,2,2028818,1012397,2,1,1,34664,2,1,1,993153,1,1,0,-15420,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,N,N,12,2028818,1,0,1,2,1012397,1404828,0,3,793,-15420,252828,0.72,-6.0990,0.69,0,0,0,793,INFO_MISSING,INFO_MISSING,N,INFO_MISSING,INFO_MISSING,TIER1
2,1,0,MALE,42,N,N,N,N,N,N,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,0,779,4,1,3,278223,23788,1,0,1,0,0,0,0,0,2,1,1,23788,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,N,N,14,278223,0,0,1,0,23788,29807,0,1,779,23788,29807,0.79,79.8067,0.10,0,0,0,779,INFO_MISSING,INFO_MISSING,N,INFO_MISSING,INFO_MISSING,TIER4
3,0,0,MALE,42,N,N,N,N,N,N,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,0,0,2,2,0,702950,608324,0,0,0,0,0,0,0,0,1,1,0,-2500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,N,N,4,702950,0,0,1,1,608324,702950,0,2,0,-2500,2950,0.86,-84.7457,1.00,0,0,0,776,N,N,N,INFO_MISSING,INFO_MISSING,TIER1
4,1,0,MALE,31,N,N,N,N,N,N,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,0,0,8,3,5,1135193,627938,0,0,0,0,2,1,1,31108,6,2,4,596830,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,N,N,4,1135193,1,0,2,1,627938,938045,0,3,0,596830,738045,0.66,80.8663,0.82,0,0,0,750,INFO_MISSING,INFO_MISSING,N,INFO_MISSING,INFO_MISSING,TIER4

In [12]:
RyG=['CIBIL_EMAIL_DOMAIN_COMPANY_FLAG1' ,'ADDRESS_WITH_COMPANY_FLAG1' ,'PAYU_DEBIT_CARD_USER' ,'PAYU_NET_BANKING_USER' ]

In [13]:
df_CIBIL2 = df_CIBIL2_2.drop(RyG,axis=1)

In [14]:
df_CIBIL2 = pd.get_dummies(df_CIBIL2, columns=['TIER_FINAL','ENRICHED_GENDER','ENRICHED_SPECIALIZATION','ENRICHED_DEGREE','ENRICHED_QUALIFICATION',
'ENRICHED_CURRENT_INDUSTRY','ENRICHED_CURRENT_COMPANY','ENRICHED_DESIGNATION','PAYU_CREDIT_CARD_USER','HIGHEST_EDUCATION_INSTI','WORK_EXPERIENE_BAND','ANNUAL_SALARY_BAND'
], dummy_na=True)

In [22]:
#list(df_CIBIL2.columns)
sorted(df_CIBIL2)

['ANNUAL_SALARY_BAND_1-4LAC',
 'ANNUAL_SALARY_BAND_11-16LAC',
 'ANNUAL_SALARY_BAND_4-7LAC',
 'ANNUAL_SALARY_BAND_7-11LAC',
 'ANNUAL_SALARY_BAND_<=1LAC',
 'ANNUAL_SALARY_BAND_>16LAC',
 'ANNUAL_SALARY_BAND_INFO_MISSING',
 'ANNUAL_SALARY_BAND_nan',
 'BL_CLOSED_LOANS_CIBIL',
 'BL_LIVE_LOANS_CIBIL',
 'BL_POS_CIBIL',
 'BL_TOTAL_LOANS_CIBIL',
 'BUREAU_CIBIL_SALARIED_FLAG',
 'BUREAU_RECENCY',
 'CC_CLOSED_LOANS_CIBIL',
 'CC_LIVE_LOANS_CIBIL',
 'CC_POS_CIBIL',
 'CC_TOTAL_LOANS_CIBIL',
 'CD_CLOSED_LOANS_CIBIL',
 'CD_LIVE_LOANS_CIBIL',
 'CD_POS_CIBIL',
 'CD_TOTAL_LOANS_CIBIL',
 'CIBIL_BUREAU_HIT_FLAG',
 'CIBIL_SCORE',
 'ECOM_CREDIT_CARD_AMEX_FLAG',
 'ECOM_CREDIT_CARD_AXIS_FLAG',
 'ECOM_CREDIT_CARD_CITI_FLAG',
 'ECOM_CREDIT_CARD_FLAG',
 'ECOM_CREDIT_CARD_HDFC_FLAG',
 'ECOM_CREDIT_CARD_HSBC_FLAG',
 'ECOM_CREDIT_CARD_ICICI_FLAG',
 'ECOM_CREDIT_CARD_PREMIUM_FLAG',
 'ECOM_CREDIT_CARD_SBI_FLAG',
 'ECOM_DEBIT_CARD_AMEX_FLAG',
 'ECOM_DEBIT_CARD_AXIS_FLAG',
 'ECOM_DEBIT_CARD_CITI_FLAG',
 'ECOM_DEBIT_CARD_FLAG',
 'ECOM_DEBIT_CARD_HDFC_FLAG',
 'ECOM_DEBIT_CARD_HSBC_FLAG',
 'ECOM_DEBIT_CARD_ICICI_FLAG',
 'ECOM_DEBIT_CARD_PREMIUM_FLAG',
 'ECOM_DEBIT_CARD_SBI_FLAG',
 'ECOM_NB_AMEX_FLAG',
 'ECOM_NB_AXIS_FLAG',
 'ECOM_NB_CITI_FLAG',
 'ECOM_NB_FLAG',
 'ECOM_NB_HDFC_FLAG',
 'ECOM_NB_HSBC_FLAG',
 'ECOM_NB_ICICI_FLAG',
 'ECOM_NB_PREMIUM_FLAG',
 'ECOM_NB_SBI_FLAG',
 'EMAIL_AVAILABLE_FLAG',
 'ENRICHED_AGE',
 'ENRICHED_CURRENT_COMPANY_N',
 'ENRICHED_CURRENT_COMPANY_Y',
 'ENRICHED_CURRENT_COMPANY_nan',
 'ENRICHED_CURRENT_INDUSTRY_N',
 'ENRICHED_CURRENT_INDUSTRY_Y',
 'ENRICHED_CURRENT_INDUSTRY_nan',
 'ENRICHED_DEGREE_N',
 'ENRICHED_DEGREE_Y',
 'ENRICHED_DEGREE_nan',
 'ENRICHED_DESIGNATION_N',
 'ENRICHED_DESIGNATION_Y',
 'ENRICHED_DESIGNATION_nan',
 'ENRICHED_GENDER_FEMALE',
 'ENRICHED_GENDER_MALE',
 'ENRICHED_GENDER_MISSING',
 'ENRICHED_GENDER_nan',
 'ENRICHED_QUALIFICATION_N',
 'ENRICHED_QUALIFICATION_Y',
 'ENRICHED_QUALIFICATION_nan',
 'ENRICHED_SPECIALIZATION_N',
 'ENRICHED_SPECIALIZATION_Y',
 'ENRICHED_SPECIALIZATION_nan',
 'GL_CLOSED_LOANS_CIBIL',
 'GL_LIVE_LOANS_CIBIL',
 'GL_POS_CIBIL',
 'GL_TOTAL_LOANS_CIBIL',
 'HIGHEST_EDUCATION_INSTI_N',
 'HIGHEST_EDUCATION_INSTI_Y',
 'HIGHEST_EDUCATION_INSTI_nan',
 'HL_CLOSED_LOANS_CIBIL',
 'HL_LIVE_LOANS_CIBIL',
 'HL_POS_CIBIL',
 'HL_TOTAL_LOANS_CIBIL',
 'LAP_CLOSED_LOANS_CIBIL',
 'LAP_LIVE_LOANS_CIBIL',
 'LAP_POS_CIBIL',
 'LAP_TOTAL_LOANS_CIBIL',
 'OTH_CLOSED_LOANS_CIBIL',
 'OTH_LIVE_LOANS_CIBIL',
 'OTH_POS_CIBIL',
 'PAYU_CREDIT_CARD_USER_N',
 'PAYU_CREDIT_CARD_USER_Y',
 'PAYU_CREDIT_CARD_USER_nan',
 'PAYU_FLAG',
 'PL_CLOSED_LOANS_CIBIL',
 'PL_LIVE_LOANS_CIBIL',
 'PL_POS_CIBIL',
 'PL_TOTAL_LOANS_CIBIL',
 'PPL_OFFER_FLAG',
 'PROSPECT_AMO_FLAG',
 'PROSPECT_DTH_FLAG',
 'PROSPECT_ECOM_FLAG',
 'PROSPECT_EMAIL_DOMAIN_COMPANY_FL',
 'PROSPECT_INSURANCE_FLAG',
 'PROSPECT_INV_FLAG',
 'PROSPECT_MBK_FLAG',
 'PROSPECT_OTH_FLAG',
 'PROSPECT_POSTPAID_FLAG',
 'PROSPECT_PREPAID_FLAG',
 'PROSPECT_SAL_FLAG',
 'PROSPECT_TRAV_FLAG',
 'RT_LIVE_OSBAL_2_SACAMT',
 'RT_live_2_TOT_SACAMT',
 'TIER_FINAL_TIER1',
 'TIER_FINAL_TIER2',
 'TIER_FINAL_TIER3',
 'TIER_FINAL_TIER4',
 'TIER_FINAL_nan',
 'TOTAL_NO_OF_CLOSED_LOANS_CIBIL',
 'TOTAL_NO_OF_LIVE_LOANS_CIBIL',
 'TOTAL_NO_OF_LOANS_CIBIL',
 'TOTAL_POS_CIBIL',
 'TOTAL_PROSPECT_AND_RA_SOURCES',
 'TOTAL_PROSPECT_SOURCES',
 'TOTAL_SANCTIONED_AMOUNT_CIBIL',
 'TOT_SACAMT',
 'TOT_SEC_live_nbr',
 'TOT_UNSEC_live_nbr',
 'TOT_live_OSBAL',
 'TOT_live_SACAMT',
 'TOT_live_nbr',
 'WORK_EXPERIENE_BAND_0-5',
 'WORK_EXPERIENE_BAND_5-10',
 'WORK_EXPERIENE_BAND_>10',
 'WORK_EXPERIENE_BAND_INFO_MISSING',
 'WORK_EXPERIENE_BAND_nan',
 'cibil_score1',
 'cibil_score_bureau',
 'dpd_15_flag',
 'dpd_30_flag',
 'dpd_90_flag',
 'live_CC_Bal',
 'live_CC_Sacamt',
 'live_CC_utilization',
 'live_HL_flag',
 'num_live_CC',
 'num_live_PL']

In [ ]:
df_CIBIL.shape

In [ ]:
df_CIBIL2.shape

In [ ]:
null_drop = ['ECOM_DEBIT_CARD_AXIS_FLAG',
'ECOM_NB_AXIS_FLAG',
'TOTAL_PROSPECT_AND_RA_SOURCES',
'cibil_score1',
'CIBIL_SCORE',
'cibil_score_bureau',
'TOTAL_NO_OF_LIVE_LOANS_CIBIL',
'TOT_live_SACAMT',
'num_live_CC',
'live_CC_Bal',
'live_CC_Sacamt',
'live_HL_flag']

In [ ]:
df_CIBIL2=df_CIBIL2.drop(null_drop,axis=1)

In [ ]:
df_CIBIL2.shape

In [ ]:
#droping variables with low model importance

In [ ]:
Ada = ['TOTAL_PROSPECT_SOURCES',
'BL_LIVE_LOANS_CIBIL',
'BL_POS_CIBIL',
'GL_TOTAL_LOANS_CIBIL',

'ECOM_CREDIT_CARD_FLAG',
'HL_TOTAL_LOANS_CIBIL',

'HL_POS_CIBIL',
'OTH_POS_CIBIL',
'dpd_30_flag',
'OTH_CLOSED_LOANS_CIBIL',
'OTH_LIVE_LOANS_CIBIL',
'BL_CLOSED_LOANS_CIBIL',
'TOT_SEC_live_nbr',
'GL_CLOSED_LOANS_CIBIL',
'PROSPECT_INV_FLAG',
'HL_LIVE_LOANS_CIBIL',
'dpd_90_flag',
'HL_CLOSED_LOANS_CIBIL',
'GL_LIVE_LOANS_CIBIL',
'LAP_POS_CIBIL',
'LAP_LIVE_LOANS_CIBIL',
'GL_POS_CIBIL',
'LAP_TOTAL_LOANS_CIBIL',
'ECOM_CREDIT_CARD_PREMIUM_FLAG',
'ECOM_CREDIT_CARD_AXIS_FLAG',
'ECOM_NB_PREMIUM_FLAG',

'PROSPECT_INSURANCE_FLAG',
'PROSPECT_DTH_FLAG',
'CIBIL_BUREAU_HIT_FLAG',
'LAP_CLOSED_LOANS_CIBIL',
'ECOM_DEBIT_CARD_PREMIUM_FLAG',
'ECOM_CREDIT_CARD_HDFC_FLAG',
'ECOM_CREDIT_CARD_ICICI_FLAG',
'ECOM_CREDIT_CARD_CITI_FLAG',
'ECOM_CREDIT_CARD_SBI_FLAG',
'ECOM_CREDIT_CARD_AMEX_FLAG',
'ECOM_CREDIT_CARD_HSBC_FLAG',
'ECOM_DEBIT_CARD_HDFC_FLAG',
'ECOM_DEBIT_CARD_ICICI_FLAG',
'ECOM_DEBIT_CARD_CITI_FLAG',
'ECOM_DEBIT_CARD_SBI_FLAG',
'ECOM_DEBIT_CARD_AMEX_FLAG',
'ECOM_DEBIT_CARD_HSBC_FLAG',
'ECOM_NB_HDFC_FLAG',
'ECOM_NB_ICICI_FLAG',
'ECOM_NB_CITI_FLAG',
'ECOM_NB_SBI_FLAG',
'ECOM_NB_AMEX_FLAG',
'ECOM_NB_HSBC_FLAG',
'ANNUAL_SALARY_BAND_INFO_MISSING',
'ENRICHED_CURRENT_COMPANY_N',
'WORK_EXPERIENE_BAND_INFO_MISSING',
'ENRICHED_QUALIFICATION_N',
'HIGHEST_EDUCATION_INSTI_N',
'ENRICHED_GENDER_MISSING',
'PROSPECT_OTH_FLAG',
'ENRICHED_DESIGNATION_N',
'ENRICHED_CURRENT_INDUSTRY_N',
'ENRICHED_DESIGNATION_N',
'ENRICHED_CURRENT_INDUSTRY_N',
'ENRICHED_SPECIALIZATION_N',
'PAYU_CREDIT_CARD_USER_N',
'ENRICHED_DEGREE_N',
'PROSPECT_MBK_FLAG',
'PROSPECT_AMO_FLAG',
'PROSPECT_TRAV_FLAG',
'PROSPECT_ECOM_FLAG',
'PAYU_FLAG',
'TOT_live_nbr',
'ECOM_DEBIT_CARD_FLAG',
'PAYU_CREDIT_CARD_USER_Y' ,'TIER_FINAL_nan' , 'ENRICHED_GENDER_nan' ,
'ENRICHED_SPECIALIZATION_nan' , 'ENRICHED_DEGREE_nan' , 'ENRICHED_QUALIFICATION_nan',
'ENRICHED_CURRENT_INDUSTRY_nan' , 'ENRICHED_CURRENT_COMPANY_nan' , 'ENRICHED_DESIGNATION_nan' ,
'PAYU_CREDIT_CARD_USER_nan' ,'HIGHEST_EDUCATION_INSTI_nan' , 'WORK_EXPERIENE_BAND_nan',
'ANNUAL_SALARY_BAND_nan'       
]

In [ ]:
df_CIBIL2=df_CIBIL2.drop(Ada,axis=1)

In [ ]:
df_CIBIL2.shape

In [ ]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [ ]:
df_CIBIL2.shape

In [ ]:
df_CIBIL2 = df_CIBIL2[df_CIBIL2.TOTAL_SANCTIONED_AMOUNT_CIBIL<200000000]

In [ ]:
df_CIBIL2.shape

In [ ]:
df_CIBIL2 = df_CIBIL2[df_CIBIL2.PL_POS_CIBIL<4000000]

In [ ]:
df_CIBIL2.shape

In [ ]:
df_CIBIL2.head()

In [ ]:
#train_test

In [ ]:
X_train = df_CIBIL2.drop(columns = "PROSPECT_SAL_FLAG")

In [ ]:
y_train = df_CIBIL2["PROSPECT_SAL_FLAG"]

In [ ]:
# Spliting the data into test and train sets
from sklearn.model_selection import train_test_split
X_train_tr,X_train_te,y_train_tr,y_train_te = train_test_split(X_train,y_train,test_size =.33,random_state=1)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, max_depth=5,
                                       n_estimators=100, oob_score=True)

In [ ]:
classifier_rf.fit(X_train_tr, y_train_tr)

In [ ]:
classifier_rf.oob_score_

In [ ]:
rf = RandomForestClassifier(random_state=42, ) #, param_grid=params_dt

# Hyperparameter Grid Search

In [ ]:
params_dt = {'max_depth' : [10,20,25,30], 'min_samples_leaf' :[0.001,0.005,0.01,0.02]}
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import roc_auc_score
grid_dt = RandomizedSearchCV(estimator=rf,param_distributions = params_dt ,scoring='roc_auc', cv = 5, n_jobs = -1)
grid_dt.fit(X_train_tr, y_train_tr)
best_model = grid_dt.best_estimator_
grid_dt.best_params_

# Predicting the output of the test cases using the algorithm created above

In [ ]:
y_pre = best_model.predict_proba(X_train_te)
y_pred_train = best_model.predict_proba(X_train_tr)

# Calculating Lift on Different probability thresholds

In [ ]:
    
sample = y_train_te[y_pre[:,1] > 0.389].shape[0]

correct = y_train_te[y_pre[:,1] > 0.389].sum()
#max_depth = 6
test_size = y_train_te.shape[0]
accuracy = correct/ sample
print(sample)
print(correct)
print(accuracy)
print(test_size)
print(sample/test_size)

In [ ]:
sample = y_train_tr[y_pred_train[:,1] > 0.60].shape[0]

correct = y_train_tr[y_pred_train[:,1] > 0.60].sum()
#max_depth = 6
test_size = y_train_tr.shape[0]
accuracy = correct/ sample
print(sample)
print(correct)
print(accuracy)
print(test_size)

In [ ]:
y_pre_class = best_model.predict(X_train_te)
y_pred_train_class = best_model.predict(X_train_tr)

In [ ]:
a=pd.DataFrame([X_train.columns,best_model.feature_importances_])

In [ ]:
a

In [ ]:
#optional
a.to_csv("a.csv",index=False)

# scoring on target data

In [ ]:
df_SCORING =  pd.read_csv("E:/Anirban_Ghosh/final_sal_semp_01.CSV",encoding='latin1')

In [ ]:
df_SCORING.shape

In [ ]:
df_SCORING.head()

In [ ]:
df_SCORING_2 = pd.get_dummies(df_SCORING, columns=['TIER_FINAL','ENRICHED_GENDER','ENRICHED_SPECIALIZATION','ENRICHED_DEGREE','ENRICHED_QUALIFICATION',
'ENRICHED_CURRENT_INDUSTRY','ENRICHED_CURRENT_COMPANY','ENRICHED_DESIGNATION','PAYU_CREDIT_CARD_USER','HIGHEST_EDUCATION_INSTI','WORK_EXPERIENE_BAND','ANNUAL_SALARY_BAND'
], dummy_na=True)

In [ ]:
#droping variables with low importance
er =['PROSPECT_SOURCE_NAME' ,'CIBIL_EMAIL_DOMAIN_COMPANY_FLAG1' ,'ADDRESS_WITH_COMPANY_FLAG1' ,'PAYU_DEBIT_CARD_USER' ,'PAYU_NET_BANKING_USER' ,
'ECOM_DEBIT_CARD_AXIS_FLAG',
'ECOM_NB_AXIS_FLAG',
'TOTAL_PROSPECT_AND_RA_SOURCES',
'cibil_score1',
'cibil_score_bureau',
'TOTAL_NO_OF_LIVE_LOANS_CIBIL',
'TOT_live_SACAMT',
'num_live_CC',
'live_CC_Bal',
'live_CC_Sacamt',
'live_HL_flag',

'TOTAL_PROSPECT_SOURCES',
'BL_LIVE_LOANS_CIBIL',
'BL_POS_CIBIL',
'GL_TOTAL_LOANS_CIBIL',

'ECOM_CREDIT_CARD_FLAG',
'HL_TOTAL_LOANS_CIBIL',

'HL_POS_CIBIL',
'OTH_POS_CIBIL',
'dpd_30_flag',
'OTH_CLOSED_LOANS_CIBIL',
'OTH_LIVE_LOANS_CIBIL',
'BL_CLOSED_LOANS_CIBIL',
'TOT_SEC_live_nbr',
'GL_CLOSED_LOANS_CIBIL',
'PROSPECT_INV_FLAG',
'HL_LIVE_LOANS_CIBIL',
'dpd_90_flag',
'HL_CLOSED_LOANS_CIBIL',
'GL_LIVE_LOANS_CIBIL',
'LAP_POS_CIBIL',
'LAP_LIVE_LOANS_CIBIL',
'GL_POS_CIBIL',
'LAP_TOTAL_LOANS_CIBIL',
'ECOM_CREDIT_CARD_PREMIUM_FLAG',
'ECOM_CREDIT_CARD_AXIS_FLAG',
'ECOM_NB_PREMIUM_FLAG',

'PROSPECT_INSURANCE_FLAG',
'PROSPECT_DTH_FLAG',
'CIBIL_BUREAU_HIT_FLAG',
'LAP_CLOSED_LOANS_CIBIL',
'ECOM_DEBIT_CARD_PREMIUM_FLAG',
'ECOM_CREDIT_CARD_HDFC_FLAG',
'ECOM_CREDIT_CARD_ICICI_FLAG',
'ECOM_CREDIT_CARD_CITI_FLAG',
'ECOM_CREDIT_CARD_SBI_FLAG',
'ECOM_CREDIT_CARD_AMEX_FLAG',
'ECOM_CREDIT_CARD_HSBC_FLAG',
'ECOM_DEBIT_CARD_HDFC_FLAG',
'ECOM_DEBIT_CARD_ICICI_FLAG',
'ECOM_DEBIT_CARD_CITI_FLAG',
'ECOM_DEBIT_CARD_SBI_FLAG',
'ECOM_DEBIT_CARD_AMEX_FLAG',
'ECOM_DEBIT_CARD_HSBC_FLAG',
'ECOM_NB_HDFC_FLAG',
'ECOM_NB_ICICI_FLAG',
'ECOM_NB_CITI_FLAG',
'ECOM_NB_SBI_FLAG',
'ECOM_NB_AMEX_FLAG',
'ECOM_NB_HSBC_FLAG',
'ANNUAL_SALARY_BAND_INFO_MISSING',
'ENRICHED_CURRENT_COMPANY_N',
'WORK_EXPERIENE_BAND_INFO_MISSING',
'ENRICHED_QUALIFICATION_N',
'HIGHEST_EDUCATION_INSTI_N',
'ENRICHED_GENDER_MISSING',
'PROSPECT_OTH_FLAG',
'ENRICHED_DESIGNATION_N',
'ENRICHED_CURRENT_INDUSTRY_N',
'ENRICHED_DESIGNATION_N',
'ENRICHED_CURRENT_INDUSTRY_N',
'ENRICHED_SPECIALIZATION_N',
'PAYU_CREDIT_CARD_USER_N',
'ENRICHED_DEGREE_N',
'PROSPECT_MBK_FLAG',
'PROSPECT_AMO_FLAG',
'PROSPECT_TRAV_FLAG',
'PROSPECT_ECOM_FLAG',
'PAYU_FLAG',
'CIBIL_SCORE' ,
'TOT_live_nbr',
'ECOM_DEBIT_CARD_FLAG',

'PAYU_CREDIT_CARD_USER_Y' ,'TIER_FINAL_nan' , 'ENRICHED_GENDER_nan' ,
'ENRICHED_SPECIALIZATION_nan' , 'ENRICHED_DEGREE_nan' , 'ENRICHED_QUALIFICATION_nan',
'ENRICHED_CURRENT_INDUSTRY_nan' , 'ENRICHED_CURRENT_COMPANY_nan' , 'ENRICHED_DESIGNATION_nan' ,
'PAYU_CREDIT_CARD_USER_nan' ,'HIGHEST_EDUCATION_INSTI_nan' , 'WORK_EXPERIENE_BAND_nan',
'ANNUAL_SALARY_BAND_nan']

In [ ]:
 df_scoring1=df_SCORING_2.drop(er,axis=1)

In [ ]:
dp =['prospect_id' , 'PROSPECT_SAL_FLAG']

In [ ]:
df_SCORING_2=df_scoring1.drop(dp,axis=1)

In [ ]:
df_SCORING_2.head()

In [ ]:
df_SCORING_2.shape

In [ ]:
imple_y=best_model.predict_proba(df_SCORING_2)

In [ ]:
imple_y

In [ ]:
df_scoring1['predicted_prob']=imple_y[:,1]

In [ ]:
df_scoring1.to_csv("sal_semp_FEB_IPOD.csv",index=False)